"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "allow-generate"
description = "Enables the generate command without any pre-configured scope."
commands.allow = ["generate"]

[[permission]]
identifier = "deny-generate"
description = "Denies the generate command without any pre-configured scope."
commands.deny = ["generate"]
